/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring_core_gradle_DI_demo;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
